---
# Here we describe every software we may want to install
- hosts: all
  roles:
  - role: osxc.packages
    brew_taps:
    - caskroom/fonts
    brew_packages:
    - git
    - zsh
    - vim
    - the_silver_searcher
    - ctags
    - reattach-to-user-namespace
    - tmux
    cask_packages:
    - font-inconsolata-for-powerline
    - iterm2
    - macvim
    - 1password
    - adobe-reader
    - alfred
    - dropbox
    - evernote
    - firefox
    - google-chrome
    - growlnotify
    - java
    - openoffice
    - skitch
    - freemind
